fc_community/fc_community/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from board.views import index, charts, WorksheetList, WorksheetCreate, Total_worksheetList, VirtualBankSystem, Workdetail, TodoList_list, addTodoView, deleteTodoView, WorksheetUpdate, WorksheetDelete, Howto_Use

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fcuser/', include('fcuser.urls')),
    path('', index, name='home'),
    path('charts/', charts, name='charts'),
    path('worksheet/', WorksheetList, name='worksheet'),
    path('totalworksheet/', Total_worksheetList, name='totalworksheet'),
    path('worksheet/create/',
         WorksheetCreate.as_view(),
         name='worksheetcreate'),
    path('virtualbanksystem/', VirtualBankSystem, name='virtualbanksystem'),
    path('worksheet/detail/<int:pk>/', Workdetail.as_view()),
    path('todo_list/', TodoList_list, name='TodoList'),
    path('addTodoItem/', addTodoView, name='addTodoView '),
    path('deleteTodoItem/<int:i>/', deleteTodoView, name='deleteTodoView'),
    path('worksheet/update/<int:pk>/',
         WorksheetUpdate.as_view(),
         name='update'),
    path('worksheet/delete/<int:pk>', WorksheetDelete.as_view(),
         name='delete'),
    path('howto_use/', Howto_Use, name='howto_use')
]

fc_community/fcuser/urls.py
from django.urls import path
from . import views
# from fcuser.views import LoginView
from fcuser.views import  RegisterView, LoginView

urlpatterns = [
    path('register/', RegisterView.as_view()),  # class는 as_view()써줘야함
    path('login/', LoginView.as_view()),
    path('logout/', views.logout, name = 'logout'),
]

fc_community/board/models.py
from django.db import models
from fcuser.models import Fcuser


class Worksheet(models.Model):
    emp_name = models.CharField(max_length=32,
                                verbose_name='직원 이름',
                                null='True')

    customer_id = models.IntegerField(verbose_name='고객번호', default=001)

    customer_name = models.CharField(max_length=256,
                                     verbose_name='고객명',
                                     null='False')
    loan_start_date = models.DateField(verbose_name='실행 예정일', null='False')

    loan_product = models.CharField(max_length=30,
                                    verbose_name='대출상품',
                                    null='True')
    loan_amount = models.IntegerField(verbose_name='대출금액', null='True')

    loan_condition = models.CharField(max_length=10,
                                      verbose_name='상환조건',
                                      null='True')
    description = models.TextField(verbose_name='메모')
    phone_number = models.CharField(max_length=13,
                                    verbose_name='핸드폰번호',
                                    null=True)
    register_date = models.DateTimeField(auto_now_add=True,
                                         verbose_name='등록날짜')
    current_process_id = models.IntegerField(verbose_name='현재 진행 척도',
                                             default=1)

    def __str__(self):
        return self.customer_name

    class Meta:
        db_table = 'WorkSheet'
        verbose_name = '업무목록'
        verbose_name_plural = '업무목록'


class LoanProduct(models.Model):
    #pk -> id
    id = models.IntegerField(verbose_name='상품코드', null=False, primary_key=True)
    loan_product_name = models.CharField(max_length=30,
                                         verbose_name='대출상품이름',
                                         null='False')

    def __str__(self):
        return self.loan_product_name

    class Meta:
        db_table = 'loan_product'
        verbose_name = '대출상품이름'
        verbose_name_plural = '대출상품이름'


class LoanProcess(models.Model):
    loan_product = models.OneToOneField('LoanProduct',
                                        models.DO_NOTHING,
                                        primary_key=True)
    loan_process_level = models.IntegerField()
    loan_process_name = models.CharField(max_length=20)

    def __str__(self):
        return self.loan_process_name

    class Meta:
        db_table = 'loan_process'
        verbose_name = '대출업무 진행단계'
        verbose_name_plural = '대출업무 진행단계'

        unique_together = (('loan_product', 'loan_process_level'))


class TodoList(models.Model):
    emp_name = models.CharField(max_length=32,
                                verbose_name='직원 이름',
                                null='True')
    register_date = models.DateTimeField(auto_now_add=True,
                                         verbose_name='등록날짜')
    content = models.TextField(max_length=100)

    def __str__(self):
        return self.content

    class Meta:
        db_table = 'TodoList'
        verbose_name = '오늘의 할일'
        verbose_name_plural = '오늘의 할일'

fc_community/board/forms.py
from django import forms


class RegisterForm(forms.Form):
    customer_id = forms.IntegerField(
        error_messages={'required': '고객번호를 입력해주세요.'}, label='고객번호 입력해요')
    customer_name = forms.CharField(
        error_messages={'required': '고객명을 입력해주세요.'},
        max_length=64,
        label='고객명')
    phone_number = forms.CharField(error_messages={'required': '연락처를 입력해주세요.'},
                                   label='연락처')
    loan_product = forms.CharField(
        error_messages={'required': '대출상품을 입력해주세요.'}, label='대출상품')
    loan_amount = forms.IntegerField(
        error_messages={'required': '대출금액을 입력해주세요.'}, label='대출금액')

    loan_start_date = forms.DateField(
        error_messages={'required': '실행 예정일을 입력해주세요.'}, label='실행 예정일을 입력해주세요')
    loan_condition = forms.CharField(
        error_messages={'required': '상환조건 여부를 입력해주세요.'}, label='상환조건여부')

    description = forms.CharField(error_messages={'required': '메모를 입력해주세요.'},
                                  label='메모')

    def clean(self):
        cleaned_data = super().clean()
        customer_id = cleaned_data.get('customer_id')
        customer_name = cleaned_data.get('customer_name')
        loan_product = cleaned_data.get('loan_product')
        loan_amount = cleaned_data.get('loan_amount')
        description = cleaned_data.get('description')
        phone_number = cleaned_data.get('phone_number')
        loan_start_date = cleaned_data.get('loan_start_date')
        loan_condition = cleaned_data.get('loan_condition')

        if not (customer_id and customer_name and loan_product and loan_amount
                and description and phone_number):
            self.add_error('customer_name', '값이 없습니다')
            self.add_error('loan_amount', '값이 없습니다')

fc_community/board/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.http import HttpResponseRedirect

from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView, UpdateView, DeleteView
from django.db import connection

from .models import Worksheet, TodoList
from fcuser.models import Fcuser
from .forms import RegisterForm

from .decorators import is_login
from datetime import datetime


# Home 화면
def index(request):
    if request.session.get('user') == None:
        return redirect('fcuser/login/')
    else:
        fcusers = Fcuser.objects.get(emp_id=request.session.get('user'))
        user = Fcuser.objects.filter(emp_id=request.session.get('user'))
        emp_name = user.get().emp_name  #로그인된 user
        request.session['emp_name'] = emp_name

        #Mysql 연동
        cursor = connection.cursor()
        # 대출 신규 예정일 5일 이내 업무 추출하는 sql문
        strSql = "select A.customer_id, A.customer_name, A.loan_product, A.loan_amount, A.loan_start_date  , C.loan_process_name, A.emp_name from WorkSheet as A Left OUTER join (select A.loan_product_name, B.loan_process_level, B.loan_process_name from loan_product as A inner join loan_process as B on a.id = b.loan_product_id) as C on a.loan_product = C.loan_product_name WHERE A.current_process_id = C.loan_process_level AND A.loan_start_date - curdate() <= 6 AND A.loan_start_date - curdate() >= 0 order by A.loan_start_date"
        result = cursor.execute(strSql)
        works = cursor.fetchall()
        connection.commit()
        within_5days_work = []
        for data in works:
            row = {
                'emp_name': data[6],
                'customer_id': data[0],
                'customer_name': data[1],
                'loan_product': data[2],
                'loan_amount': data[3],
                'loan_start_date': data[4],
                'loan_process_name': data[5]
            }
            within_5days_work.append(row)

        strsql_2 = "select A.customer_id, A.loan_product, A.loan_amount, A.emp_name from WorkSheet as A Left OUTER join (select A.loan_product_name, B.loan_process_level, B.loan_process_name from loan_product as A inner join loan_process as B on a.id = b.loan_product_id) as C on a.loan_product = C.loan_product_name WHERE A.current_process_id = C.loan_process_level and loan_process_name != '대출 실행완료'"
        result = cursor.execute(strsql_2)
        result_lst = cursor.fetchall()

        today = datetime.today().strftime("%Y년 %m월 %d일")
        connection.commit()
        work_count = 0
        # 로그인 된 user의 진행중인 업무 리스트의 갯수를 work_count에 저장
        for data in result_lst:
            if data[3] == emp_name:
                work_count += 1

        TodoList_list = TodoList.objects.all()

        return render(
            request, 'home.html', {
                'fcusers': emp_name,
                'within_5days_work': within_5days_work,
                'TodoList_list': TodoList_list,
                'work_count': work_count,
                'today': today
            })


#로그인이 된 경우에만 접근할 수 있도록 @decorator 활용
@is_login
def VirtualBankSystem(request):

    Worksheet_list = Worksheet.objects.all()
    # 업무 승인되었을 경우 진행 단계를 1단계 올림
    if request.method == 'POST':
        lst_id = request.POST.getlist('id')
        for i in lst_id:
            next_process_level = Worksheet.objects.get(
                id=int(i)).current_process_id + 1

            Worksheet.objects.filter(id=int(i)).update(
                current_process_id=next_process_level)

        return redirect('/virtualbanksystem')

    return render(request, 'VirtualBankSystem.html',
                  {'Worksheet_list': Worksheet_list})


@is_login
def WorksheetList(request):

    cursor = connection.cursor()
    strSql = "select A.* , C.loan_process_name from WorkSheet as A Left OUTER join (select A.loan_product_name, B.loan_process_level, B.loan_process_name from loan_product as A inner join loan_process as B on a.id = b.loan_product_id) as C on a.loan_product = C.loan_product_name WHERE A.current_process_id = C.loan_process_level"
    result = cursor.execute(strSql)
    works = cursor.fetchall()
    connection.commit()
    progress_datas = []
    complete_datas = []
    for data in works:
        if data[5] == 'HF 주택신용보증 전세대출':
            prog = data[11] / 5 * 100
        else:
            prog = data[11] / 6 * 100
        row = {
            'id': data[0],
            'emp_name': data[1],
            'customer_id': data[2],
            'customer_name': data[3],
            'loan_start_date': data[4],
            'loan_product': data[5],
            'loan_amount': data[6],
            'loan_condition': data[7],
            'description': data[8],
            'phone_number': data[9],
            'register_date': data[10],
            'current_process_id': data[11],
            'process_step': data[12],
            'progress': prog
        }
        if data[11] >= 6:
            complete_datas.append(row)
        elif data[5] == 'HF 주택신용보증 전세대출' and data[11] == 5:
            complete_datas.append(row)
        else:
            progress_datas.append(row)

    # Worksheet_list = Worksheet.objects.all()

    # page = request.GET.get('page', '1')  # 페이지

    # 조회
    # work_list = Worksheet.objects.order_by('-id')
    # print("work_list!!", work_list)
    # print("datas", datas)
    # 페이징처리
    # paginator = Paginator(datas, 5)  # 페이지당 10개씩 보여주기
    # page_obj = paginator.get_page(page)

    return render(request, 'Worksheet.html', {
        'progress_datas': progress_datas,
        'complete_datas': complete_datas
    })


@is_login
def Total_worksheetList(request):

    cursor = connection.cursor()
    strSql = "select A.* , C.loan_process_name from WorkSheet as A Left OUTER join (select A.loan_product_name, B.loan_process_level, B.loan_process_name from loan_product as A inner join loan_process as B on a.id = b.loan_product_id) as C on a.loan_product = C.loan_product_name WHERE A.current_process_id = C.loan_process_level"
    result = cursor.execute(strSql)
    works = cursor.fetchall()
    connection.commit()
    progress_datas = []
    complete_datas = []
    # print("works!!!", works)
    for data in works:
        if data[5] == 'HF 주택신용보증 전세대출':
            prog = data[11] / 5 * 100
        else:
            prog = data[11] / 6 * 100
        row = {
            'id': data[0],
            'emp_name': data[1],
            'customer_id': data[2],
            'customer_name': data[3],
            'loan_start_date': data[4],
            'loan_product': data[5],
            'loan_amount': data[6],
            'loan_condition': data[7],
            'description': data[8],
            'phone_number': data[9],
            'register_date': data[10],
            'current_process_id': data[11],
            'process_step': data[12],
            'progress': prog
        }
        if data[11] >= 6:
            complete_datas.append(row)
        elif data[5] == 'HF 주택신용보증 전세대출' and data[11] == 5:
            complete_datas.append(row)
        else:
            progress_datas.append(row)

    return render(request, 'Total_Worksheet.html', {
        'progress_datas': progress_datas,
        'complete_datas': complete_datas
    })


class WorksheetCreate(FormView):
    template_name = 'register_work.html'
    form_class = RegisterForm
    success_url = '/worksheet/'

    def form_valid(self, form):
        # print("user : ", self.request.session.get('user'))
        # print("emp_name : ", self.request.session.get('emp_name'))
        worksheet = Worksheet(
            customer_id=form.data.get('customer_id'),
            customer_name=form.data.get('customer_name'),
            loan_product=form.data.get('loan_product'),
            loan_amount=form.data.get('loan_amount'),
            description=form.data.get('description'),
            phone_number=form.data.get('phone_number'),
            #   지훈 코딩
            loan_start_date=form.data.get('loan_start_date'),
            emp_name=self.request.session.get('emp_name'),
            loan_condition=form.data.get('loan_condition'))
        worksheet.save()
        return super().form_valid(form)


class Workdetail(DetailView):
    template_name = 'work_detail.html'
    queryset = Worksheet.objects.all()
    context_object_name = 'Workdetail'


class WorksheetDelete(DeleteView):
    model = Worksheet
    template_name = 'work_delete.html'
    success_url = '/worksheet'


class WorksheetUpdate(UpdateView):
    model = Worksheet
    fields = [
        'customer_id', 'customer_name', 'phone_number', 'loan_product',
        'loan_amount', 'loan_start_date', 'description'
    ]
    template_name = 'work_update.html'
    context_object_name = 'worksheet'
    success_url = '/worksheet'


def charts(request):

    # 1. 직원별 대출 신규 건수를 확인하는 코드
    cursor = connection.cursor()
    strSql = "select emp_name, count(*) from worksheet group by emp_name;"
    result = cursor.execute(strSql)
    emp_count_lst = cursor.fetchall()
    connection.commit()
    # print('emp_count_lst', emp_count_lst)
    data_lst = []
    name_lst = []
    for i in range(len(emp_count_lst)):
        data_lst.append(emp_count_lst[i][1])
        name_lst.append(emp_count_lst[i][0])

    # 2. 대출 총 건수의 합을 구하는 코드
    strSql_2 = "select count(*) from worksheet;"
    result_2 = cursor.execute(strSql_2)
    total_count = cursor.fetchall()
    connection.commit()
    data_lst.append(total_count[0][0])

    # 3. 직원별 대출 금액 합을 구하는 코드
    strSql_3 = "select emp_name, round((sum(loan_amount)/100000000),2) from worksheet group by emp_name;"
    result_3 = cursor.execute(strSql_3)
    amount_lst = cursor.fetchall()
    connection.commit()
    individual_amount_lst = []
    for i in range(len(amount_lst)):
        individual_amount_lst.append(int(amount_lst[i][1]))


# 5. 상품별 대출 신규 건수를 확인하는 코드
    strSql_5 = "select loan_product, count(*) from worksheet group by loan_product;"
    result = cursor.execute(strSql_5)
    product_count = cursor.fetchall()

fc_community/board/templates/base.html
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
  {% block header %}
  {% endblock %}
</head>

<body>
  <div class="container">
    {% block contents %}
    {% endblock %}
  </div>
</body>

</html>

fc_community/board/templates/register_work.html
<!doctype html>
{% load assets % }
{% load humanize %}

<html lang="en">


<head>
   <title>신규 대출 등록 | 대출 업무 관리 시스템 </title>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
   <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
   <!-- VENDOR CSS -->
   <link rel="stylesheet" href="/assets/vendor/bootstrap/css/bootstrap.min.css">
   <link rel="stylesheet" href="/assets/vendor/font-awesome/css/font-awesome.min.css">
   <link rel="stylesheet" href="/assets/vendor/linearicons/style.css">
   <!-- MAIN CSS -->
   <link rel="stylesheet" href="/assets/css/main.css">
   <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
   <link rel="stylesheet" href="/assets/css/demo.css">
   <!-- GOOGLE FONTS -->
   <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
   <!-- ICONS -->
   <link rel="apple-touch-icon" sizes="76x76" href="/assets/img/hana_ci2.png">
   <link rel="icon" type="image/png" sizes="96x96" href="/assets/img/hana_ci2.png">
   <!-- include libraries(jQuery, bootstrap) -->
   <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

   <!-- include summernote css/js -->
   <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
   <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
   
   <script>
     $(document).ready(function () {
      $('#id_description').summernote({
        height: 200
      });
     });
   </script>
</head>

<body>
   <!-- WRAPPER -->
   <div id="wrapper">
      <!-- NAVBAR -->
      <nav class="navbar navbar-default navbar-fixed-top">
         <div class="brand">
            <a href={% url 'home' %}><img src="/assets/img/title.png" alt="HANA BANK" class="img-responsive logo"></a>
         </div>
         <div class="container-fluid">
            <div class="navbar-btn">
               <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
            </div>
            <form class="navbar-form navbar-left">
               <!--<div class="input-group">
                  <input type="text" value="" class="form-control" placeholder="Search dashboard...">
                  <span class="input-group-btn"><button type="button" class="btn btn-primary">Go</button></span>
               </div>-->
            </form>
            <div class="navbar-btn navbar-btn-right">
               <a class="btn btn-success update-pro" href={% url 'logout' %} title="로그아웃" target="_blank"> <span>로그아웃</span></a>
            </div>
            <div id="navbar-menu">
               <ul class="nav navbar-nav navbar-right">
                  <!--<li class="dropdown">
                     <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                        <i class="lnr lnr-alarm"></i>
                        <span class="badge bg-danger">5</span>
                     </a>
                     <ul class="dropdown-menu notifications">
                        <li><a href="#" class="notification-item"><span class="dot bg-warning"></span>System space is almost full</a></li>
                        <li><a href="#" class="notification-item"><span class="dot bg-danger"></span>You have 9 unfinished tasks</a></li>
                        <li><a href="#" class="notification-item"><span class="dot bg-success"></span>Monthly report is available</a></li>
                        <li><a href="#" class="notification-item"><span class="dot bg-warning"></span>Weekly meeting in 1 hour</a></li>
                        <li><a href="#" class="notification-item"><span class="dot bg-success"></span>Your request has been approved</a></li>
                        <li><a href="#" class="more">See all notifications</a></li>
                     </ul>
                  </li> 이게 종 모양-->
                  <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="lnr lnr-question-circle"></i> <span>Help</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                     <ul class="dropdown-menu">
                        <li><a href="#">Basic Use</a></li>
                        <li><a href="#">Working With Data</a></li>
                        <li><a href="#">Security</a></li>
                        <li><a href="#">Troubleshooting</a></li>
                     </ul>
                  </li>
                  <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="/assets/img/byul.png" class="img-circle" alt="Avatar"> <span> <strong>{{request.session.emp_name}}</strong> 대리님, 안녕하세요! </span> <!--<i class="icon-submenu lnr lnr-chevron-down"></i>--></a>
                     <!--<ul class="dropdown-menu">
                        <li><a href="#"><i class="lnr lnr-user"></i> <span>My Profile</span></a></li>
                        <li><a href="#"><i class="lnr lnr-envelope"></i> <span>Message</span></a></li>
                        <li><a href="#"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li>
                        <li><a href="#"><i class="lnr lnr-exit"></i> <span>Logout</span></a></li>
                     </ul>-->
                  </li>
                  <!-- <li>
                     <a class="update-pro" href={% url 'logout' %} title="Upgrade to Pro" target="_blank"><i class="fa fa-rocket"></i> <span>UPGRADE TO PRO</span></a>
                  </li> -->
               </ul>
            </div>
         </div>
      </nav>
      <!-- END NAVBAR -->
      <!-- LEFT SIDEBAR -->
      <div id="sidebar-nav" class="sidebar">
         <div class="sidebar-scroll">
            <nav>
               <ul class="nav">
                  <li><a href="{% url 'home' %}"class=""><i class="lnr lnr-home"></i> <span> 메인화면 </span></a></li>
                  <li><a href="{% url 'worksheetcreate'%}" class="active"><i class="lnr lnr-pencil"></i> <span>신규 대출 등록</span></a></li>
                        <li><a href="{% url 'worksheet'%}" class=""><i class="lnr lnr-user"></i> <span>나의 신규 리스트</span></a></li>
                  <li><a href="{% url 'totalworksheet'%}"class=""><i class="lnr lnr-inbox"></i> <span>지점 전체 신규 리스트</span></a></li> 
				  <li><a href="{% url 'charts'%}" class=""><i class="lnr lnr-chart-bars"></i> <span>업무 현황 (차트)</span></a></li>
				  <li><a href="{% url 'TodoList'%}" class=""><i class="lnr lnr-list"></i> <span>오늘의 할일</span></a></li>
				  <li><a href="{% url 'virtualbanksystem'%}" class=""><i class="lnr lnr-cog"></i> <span>가상계정단말</span></a></li>
                  
                  <!-- <li><a href="panels.html" class=""><i class="lnr lnr-cog"></i> <span>Panels</span></a></li>
                  <li><a href="notifications.html" class=""><i class="lnr lnr-alarm"></i> <span>Notifications</span></a></li> -->


                  <!--<li>
                     <a href="#subPages" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i> <span>Pages</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
                     <div id="subPages" class="collapse ">
                        <ul class="nav">
                           <li><a href="page-profile.html" class="">Profile</a></li>
                           <li><a href="page-login.html" class="">Login</a></li>
                           <li><a href="page-lockscreen.html" class="">Lockscreen</a></li>
                        </ul>
                     </div>
                  </li>-->
                  <!-- <li><a href="icons.html" class=""><i class="lnr lnr-linearicons"></i> <span>Icons</span></a></li> -->
               </ul>
            </nav>
         </div>
      </div>

        <div class="main">
         <!-- MAIN CONTENT -->
         <div class="main-content">
            <div class="container-fluid">


<div class="row mt-5">
  <div class="col-12 text-center">
    <h1>신규 대출 등록</h1> <!--대출신규 업무등록-->
  </div>
</div>


<div class="row mt-5">
  <div class="col-12">
    {{ error }}
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">

    <form method="POST" action=".">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
           <label for="{{ field.id_for_label }}">{{ field.label }}</label>
           {% if field.name == 'description' %} 
         <textarea class="form-control" name="{{ field.name }}" id="{{ field.id_for_label }}"></textarea>
           {% elif field.name == 'loan_start_date' %}
              <input type="date" class="form-control" placeholder="{{field.label}}" name= "{{ field.name }}" /> 
           {% elif field.name == 'loan_product' %}
            <select class="form-control" name = "{{ field.name }}">
               <option>HF 주택신용보증 전세대출</option>
               <option>HUG 안심 전세대출</option>
               <option>SGI 우량주택 전세대출</option>
			</select>
			{% elif field.name == 'loan_condition' %}
			<select class="form-control" name = "{{ field.name }}">
				<option>Y</option>
				<option>N</option>
			 </select>
         	{% else %}
              <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
               placeholder="{{ field.label }}" name="{{ field.name }}" />
           {% endif %}      
      	</div>
      
      
     {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      {% endfor %}
      <button type="submit" class="btn btn-primary"> 등록 </button>
    </form>
  </div>
</div>
</div>
</div>
<!-- END MAIN CONTENT -->
</div>



</div>
<!-- END WRAPPER -->
<!-- Javascript -->

<script src="assets/vendor/jquery/jquery.min.js"></script>
<script src="assets/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<script src="assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
<script src="assets/vendor/chartist/js/chartist.min.js"></script>
<script src="assets/scripts/klorofil-common.js"></script>
</body>

</html>